-- BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN (
  MANV CHAR(10) NOT NULL,
  HOTENNV NVARCHAR(30) NOT NULL,
  NGAYSINH DATETIME NOT NULL,
  GIOITINH NVARCHAR(3) NOT NULL,
  DIACHI NVARCHAR(30) NOT NULL,
  LUONG MONEY NOT NULL,
  SDT VARCHAR(20) NOT NULL,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR (30) NOT NULL,
  TRANGTHAI INT NOT NULL
);

DROP TABLE NHANVIEN

-- TẠO KHÓA CHÍNH BẢNG NHÂN VIÊN
ALTER TABLE NHANVIEN 
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)


-- BẢNG KHÁCH HÀNG
CREATE TABLE KHACHHANG (
  MAKH CHAR(10) NOT NULL,
  HOTENKH NVARCHAR(30) NOT NULL,
  DIACHI VARCHAR NOT NULL,
  SDT VARCHAR(10),
  NGAYTAO DATETIME NOT NULL,
  TRANGTHAI INT NOT NULL
);

DROP TABLE KHACHHANG
 
-- TẠO KHÓA CHÍNH BẢNG KHÁCH HÀNG
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)

-- BẢNG SẢN PHẨM
CREATE TABLE SANPHAM (
  MASP VARCHAR(10) NOT NULL,
  TENSP VARCHAR NOT NULL,
  XUATXU NVARCHAR(20) NOT NULL,
  GIANHAP DECIMAL(18,0) NOT NULL,
  GIABAN DECIMAL(18,0) NOT NULL,
  DONVITINH NVARCHAR(20) NOT NULL,
  SOLUONG INT,
  DONGIA MONEY,
  HINHANH IMAGE NOT NULL,
  KHUYENMAI INT,
  TRANGTHAIBAN BIT NOT NULL,
  MANCC VARCHAR(10) NOT NULL
);

-- TẠO KHÓA CHÍNH BẢNG SẢN PHẨM
ALTER TABLE SANPHAM
ADD CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)

-- TẠO KHÓA NGOẠI MANCC BẢNG SẢN PHẨM - NHÀ CUNG CẤP 
ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SP_NCC 
FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)

-- BẢNG HÓA ĐƠN 
CREATE TABLE HOADON (
  MAHD CHAR(10) NOT NULL,
  NGAYLAPHD DATETIME NOT NULL,
  MAKH CHAR(10) NOT NULL,
  MANV CHAR(10) NOT NULL,
  TIENKHACHDUA DECIMAL(18,0) NOT NULL,
  TIENGUIKHACH DECIMAL(18,0) NOT NULL,
  THANHTIEN DECIMAL(18,0) NOT NULL
);

DROP TABLE HOADON
-- TẠO KHÓA CHÍNH BẢNG HÓA ĐƠN 
ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY(MAHD)

-- TẠO KHÓA NGOẠI MAKH BẢNG HÓA ĐƠN - KHÁCH HÀNG
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

-- TẠO KHÓA NGOẠI MAKH BẢNG HÓA ĐƠN - NHÂN VIÊN
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

-- BẢNG CHI TIẾT HÓA ĐƠN 
CREATE TABLE CHITIETHOADON (
  MAHD CHAR(10) NOT NULL,
  MASP VARCHAR(10) NOT NULL,
  SOLUONG INT NOT NULL,
  DONGIA DECIMAL(18,0) NOT NULL,
  THANHTIEN DECIMAL(18,0) NOT NULL,
  KHUYENMAI INT
);

DROP TABLE CHITIETHOADON

-- TẠO KHÓA CHÍNH BẢNG CHI TIẾT HÓA ĐƠN 
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT PK_CHITIETHOADON PRIMARY KEY(MAHD, MASP)

-- TẠO KHÓA NGOẠI MAHD BẢNG CHI TIẾT HÓA ĐƠN - HÓA ĐƠN
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHOADON_HD FOREIGN KEY(MAHD)
REFERENCES HOADON(MAHD)

-- TẠO KHÓA NGOẠI MAHD BẢNG CHI TIẾT HÓA ĐƠN - SẢN PHẨM
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHOADON_SP FOREIGN KEY(MASP)
REFERENCES SANPHAM(MASP)

-- BẢNG NHÀ CUNG CẤP
CREATE TABLE NHACUNGCAP (
	MANCC VARCHAR(10) NOT NULL,
	TENNCC NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	TRANGTHAI INT NOT NULL
);

-- TẠO KHÓA CHÍNH BẢNG NHÀ CUNG CẤP
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT PK_NCC PRIMARY KEY(MANCC)
